import React, { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import { useLanguage } from '../lib/i18n';
import { SEO } from '../components/SEO';
import { supabase } from '../lib/supabase';
import { 
  Eye, 
  EyeOff, 
  ArrowRight, 
  CheckCircle2, 
  Mail, 
  ShieldCheck,
  LayoutDashboard,
  TrendingUp,
  FolderOpen,
  ListTodo,
  MessageSquare
} from 'lucide-react';

const content = {
  es: {
    badge: "Acceso Cliente",
    welcome: "Bienvenido,",
    subtitle: "Estás a un paso de activar tu Portal de Cliente. Aquí realizaremos el seguimiento completo de tu empresa y su nuevo sistema digital.",
    titleForm: "Crea tu Cuenta",
    descForm: "Define tus credenciales de acceso para entrar al portal en cualquier momento.",
    labelName: "Nombre Completo",
    placeholderName: "ej. Sofía Ramos",
    labelEmail: "Correo Electrónico de la Empresa",
    placeholderEmail: "ej. contacto@tuempresa.com",
    labelPassword: "Contraseña",
    placeholderPassword: "Mínimo 8 caracteres",
    btnSubmit: "Crear Cuenta y Acceder",
    btnLoading: "Configurando tu portal...",
    checkTitle: "¿Qué podrás consultar en tu Portal?",
    checkpoints: [
      {
        icon: LayoutDashboard,
        title: "Seguimiento en Tiempo Real",
        desc: "Visualiza en qué fase de desarrollo se encuentra tu sistema en cada momento (Presencia, Visibilidad, Automatización)."
      },
      {
        icon: TrendingUp,
        title: "Métricas de Rendimiento",
        desc: "Monitorea llamadas, clics e intención de búsqueda generada en vivo por tu ecosistema digital."
      },
      {
        icon: FolderOpen,
        title: "Bóveda de Entregables (Vault)",
        desc: "Accede y descarga tus contraseñas, logotipos, archivos finales y contratos de forma segura."
      },
      {
        icon: ListTodo,
        title: "Plan de Acción & Tareas",
        desc: "Revisa qué hitos faltan por completar y qué tareas tenemos asignadas ambas partes para no frenar nada."
      },
      {
        icon: MessageSquare,
        title: "Soporte Directo",
        desc: "Mantén comunicación directa con tu ingeniero de software y estratega de crecimiento asignado."
      }
    ],
    errorGeneric: "Hubo un error al crear la cuenta. Por favor, inténtalo de nuevo.",
    successRedirect: "¡Cuenta creada con éxito! Redirigiéndote al portal...",
    successEmailVerificationSent: "¡Cuenta creada! Hemos enviado un enlace de confirmación a tu correo electrónico. Por favor, verifícalo para poder acceder al portal."
  },
  en: {
    badge: "Client Onboarding",
    welcome: "Welcome,",
    subtitle: "You are one step away from activating your Client Portal. This is where we will track your company and manage your new digital growth system.",
    titleForm: "Create Your Account",
    descForm: "Define your login credentials to access the portal at any time.",
    labelName: "Full Name",
    placeholderName: "e.g. Alex Mercer",
    labelEmail: "Company Email Address",
    placeholderEmail: "e.g. contact@yourcompany.com",
    labelPassword: "Password",
    placeholderPassword: "Minimum 8 characters",
    btnSubmit: "Create Account & Enter Portal",
    btnLoading: "Setting up your portal...",
    checkTitle: "What will you track in your Portal?",
    checkpoints: [
      {
        icon: LayoutDashboard,
        title: "Real-Time Tracking",
        desc: "See exactly which development phase your digital system is in at all times (Presence, Visibility, Automation)."
      },
      {
        icon: TrendingUp,
        title: "Performance Metrics",
        desc: "Monitor live phone calls, clicks, and search intent generated by your new ecosystem."
      },
      {
        icon: FolderOpen,
        title: "Deliverables Vault",
        desc: "Access and download your credentials, logos, final project files, and contracts securely."
      },
      {
        icon: ListTodo,
        title: "Action Plan & Tasks",
        desc: "Check upcoming milestones and review tasks assigned to both of our teams to keep momentum."
      },
      {
        icon: MessageSquare,
        title: "Direct Support",
        desc: "Connect directly with your designated software engineer and growth strategist."
      }
    ],
    errorGeneric: "There was an error creating your account. Please try again.",
    successRedirect: "Account created successfully! Redirecting you to the portal...",
    successEmailVerificationSent: "Account created! We've sent a verification link to your email. Please verify it to access the portal."
  }
};

const WelcomePage = () => {
  const { language } = useLanguage();
  const location = useLocation();
  const es = language === 'es';
  const tText = content[language] || content.en;

  const [fullName, setFullName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [successMsg, setSuccessMsg] = useState('');

  // 1. Extract and clean the company name from the URL
  const [companyName, setCompanyName] = useState('');

  useEffect(() => {
    if (location.search && location.search.length > 1) {
      const searchStr = location.search.slice(1);
      let parsedName = '';

      if (searchStr.includes('=')) {
        const params = new URLSearchParams(location.search);
        parsedName = params.get('company') || params.get('name') || searchStr;
      } else {
        parsedName = decodeURIComponent(searchStr);
      }

      if (parsedName) {
        // Clean PascalCase / camelCase or underscores / hyphens / plus signs
        // e.g. "InnovativeSolutions" -> "Innovative Solutions"
        let cleaned = parsedName
          .replace(/_/g, ' ')
          .replace(/-/g, ' ')
          .replace(/\+/g, ' ');
        
        // Add spaces between camelCase/PascalCase letters
        cleaned = cleaned.replace(/([a-z])([A-Z])/g, '$1 $2');
        
        setCompanyName(cleaned);
      }
    } else {
      setCompanyName(es ? 'tu empresa' : 'your company');
    }
  }, [location.search, es]);

  // 2. Handle form submission
  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setErrorMsg('');
    setSuccessMsg('');

    try {
      // 1. Sign up the user in Supabase Auth
      const { data: signUpData, error: signUpError } = await supabase.auth.signUp({
        email: email.trim(),
        password,
        options: {
          data: {
            full_name: fullName.trim(),
            company_name: companyName
          }
        }
      });

      if (signUpError) throw signUpError;

      // 2. Try to insert client record. If it already exists, RLS or unique constraint might trigger,
      // which we will catch and ignore because it likely means the admin already prepared the profile.
      try {
        const { error: insertError } = await supabase
          .from('clients')
          .insert([
            {
              full_name: fullName.trim(),
              company_name: companyName,
              email: email.trim().toLowerCase(),
              current_phase: 1,
              total_phases: 4,
              next_milestone_title: es ? 'Sesión de Alineación Inicial' : 'Initial Alignment Session'
            }
          ]);

        if (!insertError) {
          // Fetch newly created client ID to insert default metrics & tasks
          const { data: newClient } = await supabase
            .from('clients')
            .select('id')
            .eq('email', email.trim().toLowerCase())
            .single();

          if (newClient) {
            // Add default welcome task
            await supabase.from('tasks').insert([
              {
                client_id: newClient.id,
                title: es ? 'Completar Perfil de Onboarding' : 'Complete Onboarding Profile',
                description: es 
                  ? 'Define los servicios prioritarios y adjunta tus manuales de marca o logotipos en la bóveda de archivos.' 
                  : 'Define priority services and upload your brand guidelines or logos to the deliverables vault.',
                status: 'PENDING',
                type: 'info'
              }
            ]);

            // Add default welcome metrics
            await supabase.from('metrics').insert([
              {
                client_id: newClient.id,
                label: es ? 'Impresiones Google' : 'Google Impressions',
                value: '0',
                trend: '0%',
                icon_name: 'TrendingUp',
                order_index: 0
              },
              {
                client_id: newClient.id,
                label: es ? 'Clics en Web' : 'Web Clicks',
                value: '0',
                trend: '0%',
                icon_name: 'MousePointer2',
                order_index: 1
              }
            ]);
          }
        }
      } catch (dbErr) {
        console.warn('Client profile creation was skipped or failed:', dbErr);
      }

      // 3. Automatically trigger notification to Marcos that a client just signed up
      try {
        await supabase.from('footer_leads').insert({
          email: email.trim().toLowerCase(),
          selected_service: 'Portal Access Request',
          message: `El cliente ${fullName.trim()} de la empresa ${companyName} (${email.trim()}) se ha registrado en la pantalla de bienvenida /welcome y solicita registrar su negocio en el portal de TexhCo.`
        });
      } catch (notifyErr) {
        console.warn('Auto-notification to Marcos failed:', notifyErr);
      }

      const needsVerification = signUpData?.user && !signUpData?.session;

      if (needsVerification) {
        setSuccessMsg(tText.successEmailVerificationSent);
      } else {
        setSuccessMsg(tText.successRedirect);
        // Redirect to client portal dashboard
        setTimeout(() => {
          window.location.href = '/portal';
        }, 2000);
      }

    } catch (err) {
      console.error('Registration flow error:', err);
      setErrorMsg(err.message || tText.errorGeneric);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-neutral pt-32 pb-24 px-4 flex flex-col items-center justify-center relative overflow-hidden">
      <SEO 
        title={es ? `Bienvenido ${companyName}` : `Welcome ${companyName}`}
        description={es ? "Crea tu cuenta para acceder al Portal de Texhco." : "Create your account to access the Texhco Portal."}
        url={`https://texhco.com/welcome${location.search}`}
      />

      {/* Background Accent Gradients */}
      <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-chartreuse/10 rounded-full blur-[100px] -translate-y-1/2 translate-x-1/2 pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-[500px] h-[500px] bg-obsidian/5 rounded-full blur-[100px] translate-y-1/2 -translate-x-1/2 pointer-events-none" />

      {/* Grid Pattern Overlay */}
      <div className="grid-bg-overlay opacity-5"></div>

      {/* Main Container Card */}
      <div className="w-full max-w-5xl bg-white rounded-[2.5rem] shadow-2xl border border-obsidian/5 overflow-hidden flex flex-col lg:flex-row relative z-10">
        
        {/* Left Side: Brand presentation and what they can track */}
        <div className="w-full lg:w-5/12 bg-obsidian p-8 lg:p-12 text-white flex flex-col relative justify-between">
          {/* Subtle top decoration */}
          <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-chartreuse to-white opacity-40" />

          <div>
            <span className="px-3 py-1 bg-chartreuse/20 text-chartreuse text-[10px] font-black uppercase tracking-widest rounded-full border border-chartreuse/20 w-fit mb-6 inline-block">
              {tText.badge}
            </span>

            <h2 className="text-3xl lg:text-4xl font-black uppercase tracking-tighter leading-none mb-4">
              {tText.welcome} <br />
              <span className="text-chartreuse capitalize">{companyName}</span>
            </h2>

            <p className="text-white/60 text-sm lg:text-base leading-relaxed mb-10">
              {tText.subtitle}
            </p>

            <div className="border-t border-white/10 pt-8">
              <h3 className="text-xs font-black uppercase tracking-[0.2em] text-chartreuse mb-6">
                {tText.checkTitle}
              </h3>
              
              <ul className="space-y-6">
                {tText.checkpoints.map((item, idx) => {
                  const IconComp = item.icon;
                  return (
                    <li key={idx} className="flex gap-4 items-start">
                      <div className="bg-white/5 p-2 rounded-xl border border-white/10 text-chartreuse flex-shrink-0 mt-0.5">
                        <IconComp size={16} />
                      </div>
                      <div>
                        <h4 className="font-bold text-sm text-white">{item.title}</h4>
                        <p className="text-white/50 text-xs mt-1 leading-relaxed">{item.desc}</p>
                      </div>
                    </li>
                  );
                })}
              </ul>
            </div>
          </div>

          <div className="mt-12 pt-6 border-t border-white/10 flex items-center justify-between text-[10px] text-white/40 uppercase tracking-widest font-bold">
            <span>Texh Co. Portal</span>
            <span>v2.0</span>
          </div>
        </div>

        {/* Right Side: Onboarding Signup Form */}
        <div className="w-full lg:w-7/12 p-8 lg:p-12 flex flex-col justify-center">
          
          <div className="mb-8">
            <h3 className="text-2xl font-black text-obsidian tracking-tight uppercase">
              {tText.titleForm}
            </h3>
            <p className="text-obsidian/50 text-sm mt-1">
              {tText.descForm}
            </p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-6">
            
            {/* Full Name input */}
            <div className="space-y-1.5">
              <label className="text-[10px] font-black uppercase tracking-[0.2em] text-obsidian/40 ml-4 flex items-center gap-2">
                <ShieldCheck size={12} className="text-obsidian/30" />
                {tText.labelName}
              </label>
              <input
                type="text"
                required
                placeholder={tText.placeholderName}
                value={fullName}
                onChange={(e) => setFullName(e.target.value)}
                className="w-full bg-neutral/50 border border-transparent rounded-2xl p-4 text-sm font-bold text-obsidian placeholder:text-obsidian/35 focus:ring-4 ring-chartreuse/25 focus:bg-white focus:border-obsidian/20 outline-none transition-all"
              />
            </div>

            {/* Email input */}
            <div className="space-y-1.5">
              <label className="text-[10px] font-black uppercase tracking-[0.2em] text-obsidian/40 ml-4 flex items-center gap-2">
                <Mail size={12} className="text-obsidian/30" />
                {tText.labelEmail}
              </label>
              <input
                type="email"
                required
                autocomplete="username"
                placeholder={tText.placeholderEmail}
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="w-full bg-neutral/50 border border-transparent rounded-2xl p-4 text-sm font-bold text-obsidian placeholder:text-obsidian/35 focus:ring-4 ring-chartreuse/25 focus:bg-white focus:border-obsidian/20 outline-none transition-all"
              />
            </div>

            {/* Password input */}
            <div className="space-y-1.5">
              <label className="text-[10px] font-black uppercase tracking-[0.2em] text-obsidian/40 ml-4 flex items-center gap-2">
                <ShieldCheck size={12} className="text-obsidian/30" />
                {tText.labelPassword}
              </label>
              <div className="relative">
                <input
                  type={showPassword ? "text" : "password"}
                  required
                  autocomplete="new-password"
                  placeholder={tText.placeholderPassword}
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  minLength={8}
                  className="w-full bg-neutral/50 border border-transparent rounded-2xl p-4 pr-12 text-sm font-bold text-obsidian placeholder:text-obsidian/35 focus:ring-4 ring-chartreuse/25 focus:bg-white focus:border-obsidian/20 outline-none transition-all"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-4 top-1/2 -translate-y-1/2 text-obsidian/30 hover:text-obsidian transition-colors focus:outline-none"
                  aria-label={showPassword ? "Hide password" : "Show password"}
                >
                  {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
                </button>
              </div>
            </div>

            {/* Submit Button */}
            <button
              type="submit"
              disabled={loading || !fullName || !email || password.length < 8}
              className="w-full bg-obsidian text-chartreuse py-5 rounded-2xl font-black uppercase tracking-widest text-xs hover:bg-obsidian/90 transition-all flex items-center justify-center gap-3 disabled:opacity-50 disabled:cursor-not-allowed mt-8 shadow-xl shadow-obsidian/10"
            >
              {loading ? tText.btnLoading : tText.btnSubmit}
              <ArrowRight size={14} />
            </button>
          </form>

          {/* Feedback messages */}
          {errorMsg && (
            <div className="mt-6 p-4 rounded-2xl bg-red-500/10 text-red-500 border border-red-500/20 text-xs font-bold text-center">
              {errorMsg}
            </div>
          )}

          {successMsg && (
            <div className="mt-6 p-4 rounded-2xl bg-green-500/10 text-green-600 border border-green-500/20 text-xs font-bold text-center flex items-center justify-center gap-2">
              <CheckCircle2 size={16} />
              {successMsg}
            </div>
          )}

        </div>

      </div>

    </div>
  );
};

export default WelcomePage;
